#ifdef UNIFORM_BUFFER
#undef UNIFORM_BUFFER
#define UNIFORM_BUFFER 8
#endif
#define MRT 0
#define MIRROR_MRT 1
#define BOOLEAN_MRT 2
#define LIGHT_ACCUMULATION 3
#define EDGE 4
#define PLAYER_ONE 5
#define PLAYER_TWO 6
#define OCCLUSION 7
#define OCCLUSION_DEBUG 8
#define NO_OF_SURFACES 9

#ifdef UNIFORM_BUFFER
#define UNIFORM_BUFFER_WIDTH 10.0
#endif
