#define FRAGMENT_MRT 0
#define FRAGMENT_FLAT 1
#define FRAGMENT_DEPTH 2
#define FRAGMENT_OCCLUSION_FIRST_PASS 3
#define FRAGMENT_OCCLUSION_SECOND_PASS 4
#define FRAGMENT_EDGE_DETECTION 5
#define FRAGMENT_POST_PROCESSING 6
#define FRAGMENT_UNIFORM_ENCODING 7

#define byte 255.0
#define THRESHOLD 0.5
#define COMIC_FILTER_RESOLUTION 100.0
